targets:
  $default:
    builders:
      chassis_builder:
        enabled: true
        generate_for:
          - lib/**

builders:
  chassis_builder:
    import: "package:chassis_builder/chassis_builder.dart"
    builder_factories: ["chassisBuilder"]
    build_extensions: {r"$lib$": ["app_mediator.dart"]}
    auto_apply: dependents
    build_to: source

  repository_builder:
    import: "package:chassis_builder/chassis_builder.dart"
    builder_factories: ["repositoryBuilder"]
    build_extensions: {".dart": [".handlers.dart"]}
    auto_apply: dependents
    build_to: source
    runs_before: ["chassis_builder"]
