name: chassis
description: An architectural framework for flutter applications
version: 0.0.1+3
repository: https://github.com/pierremrtn/chassis
homepage: https://affordant.gitbook.io/chassis/
topics: 
  - chassis
  - mvvm
  - cqrs
  - architecture
  - state-management

environment:
  sdk: ^3.6.2

dependencies:
  rxdart: ^0.28.0
  meta: ^1.16.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
