name: chassis
description: An architectural framework for flutter applications
version: 0.0.1
repository: https://github.com/pierremrtn/chassis
homepage: https://affordant.gitbook.io/chassis/

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  rxdart: ^0.28.0
  meta: ^1.16.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
