name: chassis_flutter
description: An architectural framework for flutter applications
version: 0.0.1+1
repository: https://github.com/pierremrtn/chassis
homepage: https://affordant.gitbook.io/chassis/

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  chassis: ^0.0.1
  rxdart: ^0.28.0
  provider: ^6.1.5
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
